input {
  # Простой вход для тестов (можно слать данные через curl)
  http {
    port => 5044
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "my-test-logs-%{+YYYY.MM.dd}"
  }
  # Дублируем в консоль контейнера для отладки
  stdout { codec => rubydebug }
}
