input {
  # Простой вход для тестов (можно слать данные через curl)
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  # Дублируем в консоль контейнера для отладки
  stdout { codec => rubydebug }
}