name: Deploy ELK Stack

on:
  push:
    branches: [ main ] # Деплой при пуше в мастер
  workflow_dispatch:   # Или кнопкой вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml,logstash_conf/,filebeat.yml" # Что копируем
          target: "~/elk-stack"

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/elk-stack
            # Авторизация в вашем зеркале (используем тот же PAT из секретов)
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            # Остановка старых контейнеров и запуск новых
            docker-compose pull
            docker-compose up -d
            # Очистка старых образов для экономии места
            docker image prune -f
