name: Deploy ELK Stack

on:
  push:
    branches: [ main ] # Деплой при пуше в мастер
  workflow_dispatch:   # Или кнопкой вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy roles
        run: |
          URL="https://${{ secrets.GITLAB_USER }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ansible_playbooks7843206/docker.git"
          sed -i "s|GITLAB_URL|$URL|g" ansible/requirements.yml
          echo "Requirements file updated."
          ansible-galaxy install -r ansible/requirements.yml

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > .ssh_key
          chmod 600 .ssh_key

      # Запуск Playbook
      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/setup_elk.yml
          # Используем правильный флаг -i
          options: |
            -i ${{ secrets.HOST }},
            --user ${{ secrets.USERNAME }}
            --private-key .ssh_key
            --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          # Создаем временный файл ключа для Ansible
          ANSIBLE_HOST_KEY_CHECKING: "False"

      # Предварительно создаем файл ключа, чтобы Ansible мог зайти на сервер
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > .ssh_key
          chmod 600 .ssh_key
