name: Deploy ELK Stack

on:
  push:
    branches: [ main ] # Деплой при пуше в мастер
  workflow_dispatch:   # Или кнопкой вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy roles
        run: |
          URL="https://${{ secrets.GITLAB_USER }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ansible_playbooks7843206/docker.git"
          sed -i "s|GITLAB_URL|$URL|g" ansible/requirements.yml
          echo "Requirements file updated."
          ansible-galaxy install -r ansible/requirements.yml

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Указываем, какие файлы и папки перенести
          source: "docker-compose.yml,filebeat.yml,logstash_conf/"
          target: "~/elk-stack"
          strip_components: 0 # Сохраняем структуру папок (для logstash_conf)

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > .ssh_key
          chmod 600 .ssh_key

      # Запуск Playbook
      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/setup_elk.yml
          # Используем правильный флаг -i
          options: |
            -i ${{ secrets.HOST }},
            --user ${{ secrets.USERNAME }}
            --private-key .ssh_key
            --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          # Создаем временный файл ключа для Ansible
          ANSIBLE_HOST_KEY_CHECKING: "False"
